[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[invariant]
runs = 100
depth = 128
fail_on_revert = true